//! Native grayscale decode for monochrome (Cs400) AVIF — imazen/zenavif#5.
//!
//! Fixtures under `tests/vectors/zenavif/` are genuine monochrome AV1
//! (no chroma planes), generated by zenavif-serialize's
//! `examples/make_mono_avif.rs` (zenrav1e `still_picture` + `Cs400`).
//!
//! The load-bearing contract: gray output is produced by the SAME range-
//! expansion kernel as the RGB path, so `gray[i] == rgb[i].r` exactly —
//! any drift between the two paths is a bug in one of them.

use std::borrow::Cow;
use zencodec::decode::{Decode as _, DecodeJob as _, DecodeOutput, DecoderConfig as _};
use zenpixels::{ChannelLayout, PixelDescriptor, PixelFormat};

const MONO_8B_FULL: &str = "tests/vectors/zenavif/mono_gradient_8b_full.avif";
const MONO_8B_LIMITED: &str = "tests/vectors/zenavif/mono_gradient_8b_limited.avif";
const MONO_10B_FULL: &str = "tests/vectors/zenavif/mono_gradient_10b_full.avif";
const MONO_5X3: &str = "tests/vectors/zenavif/mono_5x3_8b_full.avif";

fn decode_pref(data: &[u8], preferred: &[PixelDescriptor]) -> DecodeOutput {
    zenavif::AvifDecoderConfig::new()
        .job()
        .decoder(Cow::Borrowed(data), preferred)
        .expect("decoder")
        .decode()
        .expect("decode")
}

/// Per-pixel u8 gray values from a Gray8 buffer.
fn gray8_values(out: &DecodeOutput) -> Vec<u8> {
    let p = out.pixels();
    assert_eq!(p.descriptor().pixel_format(), PixelFormat::Gray8);
    let (w, h, stride) = (p.width() as usize, p.rows() as usize, p.stride());
    let bytes = p.as_strided_bytes();
    (0..h)
        .flat_map(|y| bytes[y * stride..][..w].to_vec())
        .collect()
}

/// Per-pixel R values from an Rgb8 buffer.
fn rgb8_r_values(out: &DecodeOutput) -> Vec<u8> {
    let p = out.pixels();
    assert_eq!(p.descriptor().pixel_format(), PixelFormat::Rgb8);
    let (w, h, stride) = (p.width() as usize, p.rows() as usize, p.stride());
    let bytes = p.as_strided_bytes();
    let mut v = Vec::with_capacity(w * h);
    for y in 0..h {
        let row = &bytes[y * stride..][..w * 3];
        for x in 0..w {
            let px = &row[x * 3..x * 3 + 3];
            assert_eq!(px[0], px[1], "mono RGB expansion must be R=G=B");
            assert_eq!(px[1], px[2], "mono RGB expansion must be R=G=B");
            v.push(px[0]);
        }
    }
    v
}

#[test]
fn mono_decodes_native_gray8_by_default() {
    for (path, label) in [
        (MONO_8B_FULL, "full-range"),
        (MONO_8B_LIMITED, "limited-range"),
    ] {
        let data = std::fs::read(path).expect("fixture");
        let gray = decode_pref(&data, &[]);
        let desc = gray.pixels().descriptor();
        assert_eq!(
            desc.pixel_format(),
            PixelFormat::Gray8,
            "{label}: no-preference decode of alpha-free mono is native gray"
        );
        assert_eq!((gray.pixels().width(), gray.pixels().rows()), (96, 64));

        // Kernel-parity contract vs the RGB-expanded decode.
        let rgb = decode_pref(&data, &[PixelDescriptor::RGB8_SRGB]);
        assert_eq!(
            gray8_values(&gray),
            rgb8_r_values(&rgb),
            "{label}: gray must equal the R channel of the RGB decode exactly"
        );
    }
}

#[test]
fn mono_limited_range_actually_expands() {
    // The limited fixture's coded Y is 16..=235; a correct decode expands
    // to full range. If expansion were skipped, max would be ≤235.
    let data = std::fs::read(MONO_8B_LIMITED).expect("fixture");
    let vals = gray8_values(&decode_pref(&data, &[]));
    let (min, max) = (vals.iter().min().copied(), vals.iter().max().copied());
    assert!(
        max > Some(245),
        "limited range must expand toward 255, max {max:?}"
    );
    assert!(
        min < Some(10),
        "limited range must expand toward 0, min {min:?}"
    );
}

#[test]
fn mono_10bit_decodes_native_gray16() {
    let data = std::fs::read(MONO_10B_FULL).expect("fixture");
    let gray = decode_pref(&data, &[]);
    let p = gray.pixels();
    assert_eq!(p.descriptor().pixel_format(), PixelFormat::Gray16);

    let rgb = decode_pref(&data, &[PixelDescriptor::RGB16_SRGB]);
    let rp = rgb.pixels();
    assert_eq!(rp.descriptor().pixel_format(), PixelFormat::Rgb16);

    let (w, h) = (p.width() as usize, p.rows() as usize);
    let (gs, rs) = (p.stride(), rp.stride());
    let (gb, rb) = (p.as_strided_bytes(), rp.as_strided_bytes());
    for y in 0..h {
        let grow: &[u16] = rgb::bytemuck::cast_slice(&gb[y * gs..][..w * 2]);
        let rrow: &[u16] = rgb::bytemuck::cast_slice(&rb[y * rs..][..w * 6]);
        for x in 0..w {
            assert_eq!(
                grow[x],
                rrow[x * 3],
                "gray16 must equal R of the RGB16 decode at ({x},{y})"
            );
        }
    }
}

#[test]
fn mono_gray8_preference_on_10bit_downconverts() {
    let data = std::fs::read(MONO_10B_FULL).expect("fixture");
    let gray = decode_pref(&data, &[PixelDescriptor::GRAY8_SRGB]);
    assert_eq!(
        gray.pixels().descriptor().pixel_format(),
        PixelFormat::Gray8
    );
    assert_eq!((gray.pixels().width(), gray.pixels().rows()), (96, 64));
}

#[test]
fn mono_rgb_preference_keeps_classic_expansion() {
    let data = std::fs::read(MONO_8B_FULL).expect("fixture");
    let rgb = decode_pref(&data, &[PixelDescriptor::RGB8_SRGB]);
    assert_eq!(rgb.pixels().descriptor().pixel_format(), PixelFormat::Rgb8);
    let rgba = decode_pref(&data, &[PixelDescriptor::RGBA8_SRGB]);
    assert_eq!(
        rgba.pixels().descriptor().pixel_format(),
        PixelFormat::Rgba8
    );
}

#[test]
fn mono_odd_dimensions_crop() {
    let data = std::fs::read(MONO_5X3).expect("fixture");
    let gray = decode_pref(&data, &[]);
    let p = gray.pixels();
    assert_eq!(p.descriptor().pixel_format(), PixelFormat::Gray8);
    assert_eq!(
        (p.width(), p.rows()),
        (5, 3),
        "coded-size padding must be cropped"
    );
}

#[test]
fn color_image_never_synthesizes_gray() {
    // A GRAY8 preference on a color image must NOT be satisfied by luma
    // synthesis in format negotiation — the output stays native.
    let data = std::fs::read("tests/vectors/libavif/kodim03_yuv420_8bpc.avif").expect("vector");
    let out = decode_pref(&data, &[PixelDescriptor::GRAY8_SRGB]);
    assert_ne!(
        out.pixels().descriptor().layout(),
        ChannelLayout::Gray,
        "color sources must not be silently collapsed to gray"
    );
}

#[test]
fn capabilities_and_descriptors_advertise_gray() {
    let caps = <zenavif::AvifDecoderConfig as zencodec::decode::DecoderConfig>::capabilities();
    assert!(caps.native_gray());
    let descs =
        <zenavif::AvifDecoderConfig as zencodec::decode::DecoderConfig>::supported_descriptors();
    assert!(descs.contains(&PixelDescriptor::GRAY8_SRGB));
    assert!(descs.contains(&PixelDescriptor::GRAY16_SRGB));
}

#[test]
fn streaming_mono_emits_gray_strips_matching_buffered() {
    use zencodec::decode::StreamingDecode as _;

    let data = std::fs::read(MONO_8B_FULL).expect("fixture");
    let buffered = decode_pref(&data, &[]);
    let bp = buffered.pixels();
    assert_eq!(bp.descriptor().pixel_format(), PixelFormat::Gray8);

    let mut dec = zenavif::AvifDecoderConfig::new()
        .job()
        .streaming_decoder(Cow::Borrowed(&data), &[])
        .expect("streaming_decoder");
    let (w, h) = (dec.info().width, dec.info().height);
    assert_eq!((w, h), (96, 64));
    let mut rows_seen = 0u32;
    while let Some((y, strip)) = dec.next_batch().expect("next_batch") {
        assert_eq!(
            strip.descriptor().pixel_format(),
            PixelFormat::Gray8,
            "mono streaming must emit gray strips"
        );
        for r in 0..strip.rows() {
            assert_eq!(
                strip.row(r),
                bp.row(y + r),
                "strip row {} differs from buffered",
                y + r
            );
            rows_seen += 1;
        }
    }
    assert_eq!(rows_seen, h);
}

/// The non-zencodec `decode_with` API keeps its historical RGB output for
/// monochrome (native gray is a zencodec-negotiation opt-in only).
#[test]
fn legacy_decode_with_stays_rgb() {
    let data = std::fs::read(MONO_8B_FULL).expect("fixture");
    let out = zenavif::decode_with(
        &data,
        &zenavif::DecoderConfig::new().prefer_8bit(true),
        &enough::Unstoppable,
    )
    .expect("decode");
    assert!(
        out.try_as_imgref::<rgb::Rgb<u8>>().is_some(),
        "legacy API must keep expanding mono to RGB8"
    );
}
